# Generated by Django 4.2.18 on 2025-02-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='test',
            name='num_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
