# Generated by Django 4.2.18 on 2025-02-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_platform', '0002_test_avg_rating_test_num_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='avg_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='num_attempts',
            new_name='views',
        ),
    ]
