# Generated by Django 4.2.18 on 2025-02-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_add_answers',
            field=models.BooleanField(default=False, verbose_name='Может добавлять ответы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_add_categories',
            field=models.BooleanField(default=False, verbose_name='Может добавлять категории'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_add_questions',
            field=models.BooleanField(default=False, verbose_name='Может добавлять вопросы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_add_tests',
            field=models.BooleanField(default=False, verbose_name='Может добавлять тесты'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_answers',
            field=models.BooleanField(default=False, verbose_name='Может удалять ответы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_categories',
            field=models.BooleanField(default=False, verbose_name='Может удалять категории'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_questions',
            field=models.BooleanField(default=False, verbose_name='Может удалять вопросы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_tests',
            field=models.BooleanField(default=False, verbose_name='Может удалять тесты'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_answers',
            field=models.BooleanField(default=False, verbose_name='Может редактировать ответы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_categories',
            field=models.BooleanField(default=False, verbose_name='Может редактировать категории'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_questions',
            field=models.BooleanField(default=False, verbose_name='Может редактировать вопросы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_tests',
            field=models.BooleanField(default=False, verbose_name='Может редактировать тесты'),
        ),
    ]
